## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO.init.mac
##
## Initialization macro to simulate Bi-214 radioactive decays from the
## copper plate of the tracking plane in the NEXT-10. detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics

/nexus/RegisterGeometry NextHDDEMO

#/nexus/RegisterGenerator IonGenerator
/nexus/RegisterGenerator ScintillationGenerator

/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterEventAction DefaultEventAction
/nexus/RegisterTrackingAction OpticalTrackingAction

/nexus/RegisterMacro macros/NEXTHDDEMO_.config.mac
/nexus/RegisterDelayedMacro macros/physics/Bi214.mac
