## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO_Na.init.mac
##
## Initialization macro to simulate Na-22 decays in the NEXT-HDDEMO geometry
## without optical photons or sensor response.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics
#/PhysicsList/RegisterPhysics G4OpticalPhysics

/nexus/RegisterGeometry NextHDDEMOOpticalGeometry

/nexus/RegisterGenerator IonGenerator


/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterEventAction DefaultEventAction

/nexus/RegisterTrackingAction DefaultTrackingAction

# No optical stepping action is needed when optical photons are disabled.

/nexus/RegisterMacro macros/NEXTHDDEMO_Na.config.mac
