## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO_full.config.mac
##
## Configuration macro to simulate Kr-83 decays in the NEXT-10. geometry
## with generation and transportation of optical photons.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# /process/em/verbose 0

##### GEOMETRY #####
/Geometry/NextHDDEMO/pressure 6.0 bar
/Geometry/NextHDDEMO/max_step_size 1. mm
/Geometry/NextHDDEMO/field_cage_vis 1

## EL______________________________________________________
/Geometry/NextHDDEMO/elfield false
/Geometry/NextHDDEMO/EL_field 13 kV/cm

## difusion______________________________________________________
/Geometry/NextHDDEMO/drift_transv_diff 0. mm/sqrt(cm)
/Geometry/NextHDDEMO/drift_long_diff 0. mm/sqrt(cm)
/Geometry/NextHDDEMO/ELtransv_diff 0. mm/sqrt(cm)
/Geometry/NextHDDEMO/ELlong_diff 0. mm/sqrt(cm)


## fibers______________________________________________________
/Geometry/NextHDDEMO/fiber_type Y11 ### (Y11, B2)
/Geometry/NextHDDEMO/coated true
/Geometry/NextHDDEMO/panels_visibility true

## sensor______________________________________________________
/Geometry/NextHDDEMO/sensor_type SiPM_Hamamatsu ### (PERFECT, SiPM_FBK, SiPM_Hamamatsu, PMT)
/Geometry/NextHDDEMO/fibers_visibility false

## teflon______________________________________________________
/Geometry/NextHDDEMO/panels_visibility true


# /process/optical/processActivation Cerenkov false

##### GENERATOR #####
# /Geometry/NextHDDEMO/vertex_zpos ACTIVE_END ### (ACTIVE_CENTER, ACTIVE_END)

/Geometry/NextHDDEMO/vertex_zpos ACTIVE_END

##### GENERATOR #####

# Posicion de la fuente de 22Na
/Geometry/NextHDDEMO/specific_vertex 225. 0. 135. mm    
/Generator/Na22Generator/region AD_HOC

# Single Particle____________________________________________
# /Generator/SingleParticle/particle geantino
# /Generator/SingleParticle/min_energy 1 MeV
# /Generator/SingleParticle/max_energy 1 MeV
# /Generator/SingleParticle/region CENTER
# /Generator/SingleParticle/momentum 0 0 0

## Kr38m______________________________________________________
#/Generator/Kr83mGenerator/region ACTIVE_END

## bb______________________________________________________
# use C++ translation of DECAY0
#/Generator/Decay0Interface/inputFile none

#/Generator/Decay0Interface/EnergyThreshold 0.5
#/Generator/Decay0Interface/Ba136FinalState 0
#/Generator/Decay0Interface/region ACTIVE

#### bb0nu________________
# for 0 neutrino  bb to Barium Ground state.
#/Generator/Decay0Interface/Xe136DecayMode 1

#### bb2nu________________
# for 2 neutrino  bb to Barium Ground state.
#/Generator/Decay0Interface/Xe136DecayMode 4


##### PHYSICS #####

/PhysicsList/Nexus/clustering          true
/PhysicsList/Nexus/drift               true
/PhysicsList/Nexus/electroluminescence true
/PhysicsList/Nexus/photoelectric       true

##### RANDOM_SEED #####
/nexus/random_seed -1

##### PERSISTENCY #####
/nexus/persistency/output_file 6barXe
