## ----------------------------------------------------------------------------
## nexus | NEXTHDDEMO_Kr.init.mac
##
## Initialization macro to simulate Kr-83 decays in the NEXT-HDDEMO geometry
## without optical photons or sensor response.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

/nexus/RegisterGeometry NextHDDEMOOpticalGeometry

/nexus/RegisterGenerator Kr83mGenerator


/nexus/RegisterPersistencyManager PersistencyManager

/nexus/RegisterRunAction DefaultRunAction
/nexus/RegisterEventAction DefaultEventAction

/nexus/RegisterTrackingAction DefaultTrackingAction

# No optical stepping action is needed when optical photons are disabled.

/nexus/RegisterMacro macros/NEXTHDDEMO_Kr.config.mac
